@baseUrl = http://localhost:3000/api/v1
@apiKey = 123456
@token = supersecretkey

### 1. Crear producto
POST {{baseUrl}}/productos
Content-Type: application/json

{
    "producto": "Laptop Estudio",
    "stockAmount": 10
}

### 2. Listar productos
GET {{baseUrl}}/productos

### 3. Obtener producto por ID (Si no funciona es porque no hay elementos en el listado, crear uno primero y colocar Id aca)
@productoId = 692e1f985c707c49b972e61c
GET {{baseUrl}}/productos/{{productoId}}

### 4. Intento de update sin autenticación (Debe tirar 401)
PUT {{baseUrl}}/productos/{{productoId}}
Content-Type: application/json

{
    "stockAmount": 15
}

### 5. Update con x-api-key válida
PUT {{baseUrl}}/productos/{{productoId}}
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "stockAmount": 20
}

### 6. Update con Token Bearer válido
PUT {{baseUrl}}/productos/{{productoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "producto": "Pc Gamer Pro con RTX 4090 super cara"
}

### 7. Delete protegido (con API Key)
DELETE {{baseUrl}}/productos/{{productoId}}
x-api-key: {{apiKey}}

### 8. Generar y descargar CSV de Albums
GET {{baseUrl}}/albums/csv
